[package]
name = "DevCleaner"
version = "0.1.0"
edition = "2024"

[dependencies]
trash = "3.1.2"
clap = { version = "4.5.1", features = ["derive"] }
rayon = "1.8"
num_cpus = "1.16"
indicatif = "0.17"
console = "0.15"
walkdir = "2.4"
